---
title: "About me"
site: distill::distill_website
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

I am a postdoctoral researcher in the Department of Statistics at the University of Pennsylvania, working with [Gene Katsevich](https://ekatsevi.github.io) (although I am physically based in Boston from July 2023). Previously, I completed my PhD in Statistics at Carnegie Mellon University under the joint supervision of [Kathryn Roeder](http://www.stat.cmu.edu/~roeder/) and Gene Katsevich. I will be joining the Harvard Biostatistics Department as a postdoctoral researcher in January 2024, where I will work with [Xihong Lin](https://content.sph.harvard.edu/xlin/index.html).

I like to work within the connective tissue that binds together the sciences of genomics, statistics, and computing. Most of my research is motivated by the goal of [understanding noncoding variation in the human genome](https://arxiv.org/pdf/2307.13708.pdf). I am especially interested in the following areas.

-   **Genomics**: single-cell applications, in particular single-cell CRISPR screens

-   **Statistics**: independence and conditional independence testing, robust inference, measurement error

-   **Computing**: algorithms and data structures for single-cell data, clouds and clusters

Here are my [email](email.html), [Github](https://github.com/Timothy-Barry), and [CV](ResumeCv/timsResume.pdf). I am excited to chat/work with biologists. Feel free to shoot an email or open a Github issue to get in touch.
