---
title: "A streamlined guide to making an R package in 2021"
description: |
  A recipe for quickly making an R package.
author:
  - name: Tim Barry
    url: https://timothy-barry.github.io
date: 03-06-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---

This post contains a short, simple recipe for making an R package. As an example I will create `simulatr`, a package intended to facilitate portable and scalable simulation studies. I will store `simulatr` locally in the directory "~/research_code/simulatr" and remotely on Github under the repository "timothy-barry/simulatr." This post assumes some working knowledge of R and Git/Github.

# 1. Initialization

- Open a new Rstudio window. Call `library(devtools)`.
- Call `create_package("~/research_code/simulatr")`. This will create a package called `simulatr` in the directory `research_code` and open a new R studio window. 
- Close the original window and navigate to the new window. Again call `library(devtools)`.
- Call `use_git()`. This initializes a git repository and adds the relevant files to `.gitignore`.
- R will ask if it is OK to make a commit; click yes. Answer the subsequent questions according to your preference (the answers do not matter much).
- Open your browser and navigate to Github. Create a new repository, setting the name of the repository to the name of your package (in this case, "simulatr"). Because you are importing an existing repository, do *not* initialize the repository with a README, gitignore, or license.
- Open the terminal on your local machine. Change directories to the package directory.

```
cd ~/research_code/simulatr
```
Set the remote and make your initial push as follows.
```
git remote add origin https://github.com/timothy-barry/simulatr.git
git branch -M main
git push -u origin main
```
- Open R studio. Click "DESCRIPTION" in the files pane. Update the fields "Title," "Authors@R", and "Description."
  - **Title**: a one-line description of what the package does, written in title-case and without periods. For example, "Portable and Scalable Simulations".
  - **Authors@R**: Your first name, last name, role, email, and ORCID. Of the roles that are available, the most important are "aut" (package author), "cre" (package maintainer), "ctb" (package contributor), and "ths" (thesis advisor). You can add multiple persons by concatenating person constructors using the `c` operator, i.e., `c(person(...), person(...))`.
  - **Description**: A one-paragraph description of what the package does, emphasizing what makes the package unique. For example, "Simulation studies play a crucial role in the development and assessment of statistical methods. However, writing portable and scalable simulation code is challenging. `Simulatr` decouples the *specification* of a simulation from the *execution* of a simulation, enabling users to develop a simulation study on their laptop and then seamlessly run the simulation at-scale on a distributed computing platform. Supported platforms include high-performance computing clusters and cloud computing services (e.g., Microsoft Azure, Amazon Web Services, etc.)."

- Update the package license. You can use an MIT license by calling `use_mit_license()` in the console.

- Update the README file, which serves as the landing page for the Github repository. Call `use_readme_rmd()` in the console, edit the `README.Rmd` file that appears on the screen, and click "Knit." As a starting point I like to copy and paste the paragraph I wrote for the DESCRIPTION under the initial header of `README.Rmd`.


# 2. Add a function.

The basic unit of R is the function; we build packages by gradually adding functions.

i. - use `use_r()` to add a new R file.
- document using Roxygen; if exported, use @export tag; if not, use @noRd. Document several related methods simultaneously; use NULL, then add @Rdname to each function.
Use `use_package()` to indicate a package is being used.
ii. `load_all()` to manually load, and `document()` to generate documentation.
iii. `check()`
iv. `use_testthat()` to initialize the test directory, and `use_test()` to add a test script.

# 3. Add data to the package

- To add standard .rda data to the package, use `use_data_raw()`; this will create a directory /data-raw and a file DATASET.R within the directory.
- Modify DATASET.R, creating the data. At the end of the script, use use_data(x,y,z) to save the objects as .rda files in the /data directory. After loading the package, you can access the data using the `data` function.
- Document the data. Type `use_this("data")` to create a new file `data.R` inside the /R directory. 

# 4. Create a website

- Turn package into pkgdown website via `usethis::use_pkgdown()`.
- Update the site via `pkgdown::build_site()`.
