---
title: "CRISPR"
description: |
  CRISPR is a technology for genome editing and modification.
author:
  - name: Tim Barry
    url: https://timothy-barry.github.io
date: 09-18-2020
output:
  distill::distill_article:
    self_contained: false
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

* CRISPR is tool for genome editing and modificaiton.
* CRISPR can be used for several tasks:
  + Progamming a small mutation
  + Inserting a new sequence of DNA
  + Removing a segment of DNA
  + Activating or repressing a segment of DNA, like an enhancer or promoter.
* CRISPR has become an important tool in biology research.
* To understand CRISPR, we must understand some basic biology related to bacterial immune systems and DNA repair in eukaryotic cells.

## The bacterial immune system

* A phage (virus) injects its DNA into the bacterial cell.
* The bacterium "captures" a portion of the phage DNA and incorporates it into its own genome.
* Several parts of the bacterial genome are transcribed: the tracrRNA, Cas9 protein, and the viral genome (forming crRNA).
* The tracr RNA, Cas9 protein, and crRNA unite to form the CRISPR/Cas9 complex.
* The crRNA guides the complex to a newly-inject viral genome, and the Cas9 protein chops it up.

## DNA repair in eukaryotic cells

* Double-stranded breaks frequently occur in DNA. Eukaryotic cells have two ways of repairing these double-stranded breaks: Non-homologous end joining (NHEJ) and homology-directed repair (HDR).
* NHEJ "glues" the ends back together with some error (i.e., nucleotide insertions or deletions). Most regions of the genome are not genes, and so this is tolerated.
* Homology-directed repair makes a more precise repair than NHEJ; it relies on the presence of a nearby homologous DNA segment.

## CRISPR technology

* Mutating a gene at a certain location through NHEJ can deactivate it through a frame-shift mutation.
* Homology-directed repair allows the researcher to insert a new segment of DNA at a location of interest.
* Delivery of the guide RNA (tracrRNA + crRNA) and Cas9 protein.
* Verifying a mutation through screens.
* dCas9 is a deactivated version of Cas9; by fusing protieins to the dCas9 (like transcriptional activators or repressors), scientists can modulate or repress transcription of certain genomic regions.